name: Update Images

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  update-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Make bash script executable
      run: chmod +x update_images.bash

    - name: Run update script
      run: ./update_images.bash

    - name: Commit and push changes
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add -A
        git commit -m "Update README images"
        git push
